version: '3.8'

services:

  web:
    build: .
    ports:
      - 8004:8000
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - .:/usr/src/app
      - db-data:/etc/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DB_FILE=sqlite:////etc/data/internal.db
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - .:/usr/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis

  redis:
    image: redis:7
    ports:
        - 6379:6379
volumes:
  db-data: